#POST http://13.125.236.67:8080/getKakaoAuth
POST http://localhost:8080/recommendCabinet
Content-Type: application/json

{
  "category_idx": 1,
  "start": "2016-01-01 11:11:11",
  "end": "2016-01-01T10:24"
}

###