#POST http://13.125.236.67:8080/apply
POST http://localhost:8080/recommendCabinet
Content-Type: application/json

{
  "category_idx": 1,
  "start": [
    2016,
    1,
    1,
    10,
    10,
    10
  ],
  "end": [
    2016,
    1,
    1,
    11,
    10,
    11
  ],
  "recommend": 1
}

###